<?php

namespace tests;
use PHPUnit\Framework\TestCase;
use Users\Users;

class UsersTest extends TestCase
{
    private static Users $newUser;

    public static function setUpBeforeClass(): void
    {
        self::$newUser = new Users();
        self::$newUser->setName("Hegabovic");
        self::$newUser->setEmail("abdallahhegab192@gmail.com");
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public function testGetUserName(){
        $this->assertTrue(
            self::$newUser->getName() == "Hegabovic"
        );
    }
}